/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import dao.RedeemDAO;
import dao.UserDAO;
import helper.Sessions;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import view.auth.FormLogin;

/**
 *
 * @author HYPE AMD
 */
public class FormTukarPoint extends javax.swing.JFrame {

    private DefaultTableModel model;
    private int selectedRedeemId = -1;
    private String selectedStatus = null;
    private int selectedPoin = 0;
    TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form TukarPoint
     */
    public FormTukarPoint() {
        if (Sessions.user == null) {
            JOptionPane.showMessageDialog(this,
                    "Silakan login terlebih dahulu");
            new FormLogin().setVisible(true);
            return;
        }
        initComponents();

        cbReward.removeAllItems();
        cbReward.addItem("Pilih Hadiah");
        cbReward.addItem("Voucher Pulsa Rp10.000 (100)");
        cbReward.addItem("Totebag Ramah Lingkungan (150)");
        cbReward.addItem("Botol Minum Reusable (200)");
        cbReward.addItem("Bibit Tanaman (50)");
        model = new DefaultTableModel();
        tblRedeem.setModel(model);
        model.addColumn("ID_Redeem");
        model.addColumn("Hadiah");
        model.addColumn("Poin digunakan");
        model.addColumn("Tanggal Penukaran");
        model.addColumn("Status");
        tampilPoin();
        loadData();
        lblInfo.setVisible(false);
        search1.setText("Cari data penukaran");
        search1.setForeground(Color.GRAY);
        sorter = new TableRowSorter<>((DefaultTableModel) tblRedeem.getModel());
        tblRedeem.setRowSorter(sorter);

        search1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filter();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filter();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filter();
            }

            private void filter() {
                String keyword = search1.getText();

                if (keyword.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                    lblInfo.setVisible(false);
                    return;
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));

                    if (tblRedeem.getRowCount() == 0) {
                        lblInfo.setVisible(true);
                    } else {
                        lblInfo.setVisible(false);
                    }
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPickup = new javax.swing.JTable();
        btnKonfirmasi1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPoin = new javax.swing.JLabel();
        cbReward = new javax.swing.JComboBox<>();
        MenuPanel2 = new javax.swing.JPanel();
        btnPanduan2 = new javax.swing.JButton();
        btnSetor3 = new javax.swing.JButton();
        btnTukarPoint3 = new javax.swing.JButton();
        btnMenuUtama3 = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();
        search1 = new javax.swing.JTextField();
        btnUbah1 = new javax.swing.JButton();
        btnKonfirmasi2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRedeem = new javax.swing.JTable();
        lblInfo = new javax.swing.JLabel();

        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(153, 204, 0));
        btnUbah.setText("Ubah Data");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 204, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detail Setoran Sampah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        tblPickup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPickup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPickupMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPickup);

        jScrollPane1.setViewportView(jScrollPane4);

        btnKonfirmasi1.setBackground(new java.awt.Color(153, 204, 0));
        btnKonfirmasi1.setText("Konfimasi");
        btnKonfirmasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasi1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(153, 204, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Pilih Hadiah");

        jLabel1.setBackground(new java.awt.Color(153, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 0));
        jLabel1.setText("Tukar EcoPoint");

        jPanel3.setBackground(new java.awt.Color(153, 204, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EcoPoint Saat ini : ");

        lblPoin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPoin.setForeground(new java.awt.Color(255, 255, 255));
        lblPoin.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPoin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        MenuPanel2.setBackground(new java.awt.Color(153, 204, 0));

        btnPanduan2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPanduan2.setForeground(new java.awt.Color(153, 204, 0));
        btnPanduan2.setText("Panduan");
        btnPanduan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanduan2ActionPerformed(evt);
            }
        });

        btnSetor3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSetor3.setForeground(new java.awt.Color(153, 204, 0));
        btnSetor3.setText("Setor");
        btnSetor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetor3ActionPerformed(evt);
            }
        });

        btnTukarPoint3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTukarPoint3.setForeground(new java.awt.Color(153, 204, 0));
        btnTukarPoint3.setText("Tukar Point");
        btnTukarPoint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTukarPoint3ActionPerformed(evt);
            }
        });

        btnMenuUtama3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuUtama3.setForeground(new java.awt.Color(153, 204, 0));
        btnMenuUtama3.setText("Home");
        btnMenuUtama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtama3ActionPerformed(evt);
            }
        });

        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(153, 204, 0));
        btnLogout2.setText("Logout");
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel2Layout = new javax.swing.GroupLayout(MenuPanel2);
        MenuPanel2.setLayout(MenuPanel2Layout);
        MenuPanel2Layout.setHorizontalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPanduan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSetor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTukarPoint3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUtama3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        MenuPanel2Layout.setVerticalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnMenuUtama3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPanduan2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSetor3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTukarPoint3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search1FocusLost(evt);
            }
        });

        btnUbah1.setBackground(new java.awt.Color(153, 204, 0));
        btnUbah1.setText("Ubah Data");
        btnUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah1ActionPerformed(evt);
            }
        });

        btnKonfirmasi2.setBackground(new java.awt.Color(153, 204, 0));
        btnKonfirmasi2.setText("Konfimasi");
        btnKonfirmasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasi2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 204, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Detail Setoran Sampah");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        tblRedeem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRedeem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRedeemMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblRedeem);

        jScrollPane2.setViewportView(jScrollPane5);

        lblInfo.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(153, 204, 0));
        lblInfo.setText("Data Tidak Ditemukan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKonfirmasi2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUbah1)
                                        .addGap(110, 110, 110))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                                        .addGap(15, 15, 15))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbReward, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(309, 309, 309))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbReward, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah1)
                    .addComponent(btnKonfirmasi2))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblInfo)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(MenuPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanduan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanduan2ActionPerformed
        // TODO add your handling code here:
        FormPanduan panduan = new FormPanduan();

        panduan.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnPanduan2ActionPerformed

    private void btnSetor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetor3ActionPerformed
        // TODO add your handling code here:
        FormSetor setor = new FormSetor();
        setor.setLocationRelativeTo(null); // Membuat window muncul di tengah
        setor.setVisible(true);
        this.dispose(); //
    }//GEN-LAST:event_btnSetor3ActionPerformed

    private void btnTukarPoint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTukarPoint3ActionPerformed
        // TODO add your handling code here:
        FormTukarPoint ftp = new FormTukarPoint();
        ftp.setLocationRelativeTo(null); // Agar muncul di tengah layar
        ftp.setVisible(true);

        // Menutup Dashboard
        this.dispose();
    }//GEN-LAST:event_btnTukarPoint3ActionPerformed

    private void btnMenuUtama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtama3ActionPerformed
        // TODO add your handling code here:
        new DashboardUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuUtama3ActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

        Sessions.logout();

        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_searchFocusLost

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnKonfirmasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasi1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnKonfirmasi1ActionPerformed

    private void tblPickupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPickupMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tblPickupMouseClicked

    private void search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusGained
        // TODO add your handling code here:
        if (search1.getText().equals("Cari data penukaran") && search1.getForeground().equals(Color.GRAY)) {
            search1.setText("");
            search1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_search1FocusGained

    private void search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusLost
        // TODO add your handling code here:
        if (search1.getText().isEmpty()) {
            search1.setText("Cari data penukaran");
            search1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_search1FocusLost

    private void btnUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah1ActionPerformed
        // TODO add your handling code here:
        if (selectedRedeemId == -1 || selectedStatus == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data penukaran terlebih dahulu");
            return;
        }

        if (!"diproses".equalsIgnoreCase(selectedStatus)) {
            JOptionPane.showMessageDialog(this,
                    "Data tidak dapat diubah karena sudah diproses admin");
            return;
        }

        if (cbReward.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih hadiah terlebih dahulu");
            return;
        }

        String reward = cbReward.getSelectedItem().toString();
        int poinBaru = ambilPoinDariReward(reward);

        if (poinBaru <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Hadiah tidak valid");
            return;
        }

        int poinUser = Sessions.user.getPoin();

        if (poinUser < poinBaru) {
            JOptionPane.showMessageDialog(this,
                    "EcoPoint tidak mencukupi\n"
                    + "Poin Anda : " + poinUser + "\n"
                    + "Poin Dibutuhkan : " + poinBaru);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin mengubah penukaran hadiah?\n\n"
                + "Hadiah : " + reward + "\n"
                + "Poin   : " + poinBaru,
                "Konfirmasi Ubah Penukaran",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        RedeemDAO dao = new RedeemDAO();
        boolean sukses = dao.updateRedeemUser(
                selectedRedeemId,
                reward,
                poinBaru
        );

        if (sukses) {
            JOptionPane.showMessageDialog(this,
                    "Data penukaran berhasil diperbarui");
            loadData();
            resetSelection();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal memperbarui data");
        }


    }//GEN-LAST:event_btnUbah1ActionPerformed

    private void btnKonfirmasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasi2ActionPerformed
        // TODO add your handling code here:
        int idUser = Sessions.user.getId_user();
        int poinUser = Sessions.user.getPoin();

        if (cbReward.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Pilih hadiah terlebih dahulu");
            return;
        }

        String reward = cbReward.getSelectedItem().toString();

        int poinDipakai = ambilPoinDariReward(reward);

        if (poinDipakai <= 0) {
            JOptionPane.showMessageDialog(this, "Hadiah tidak valid");
            return;
        }

        if (poinDipakai > poinUser) {
            JOptionPane.showMessageDialog(this, "Poin tidak mencukupi");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Tukar poin sebanyak " + poinDipakai + " ?",
                "Konfirmasi Penukaran",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean sukses = RedeemDAO.tukarPoin(idUser, reward, poinDipakai);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Penukaran berhasil, menunggu diproses admin");

            Sessions.user.setPoin(poinUser - poinDipakai);

            lblPoin.setText(String.valueOf(Sessions.user.getPoin()));
            loadData();

        } else {
            JOptionPane.showMessageDialog(this, "Penukaran gagal");
        }


    }//GEN-LAST:event_btnKonfirmasi2ActionPerformed

    private void tblRedeemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRedeemMouseClicked
        // TODO add your han  dling code here:

        int row = tblRedeem.getSelectedRow();

        selectedRedeemId = Integer.parseInt(
                tblRedeem.getValueAt(row, 0).toString()
        );

        selectedStatus = tblRedeem.getValueAt(row, 4).toString();
        selectedPoin = Integer.parseInt(
                tblRedeem.getValueAt(row, 2).toString()
        );

        cbReward.setSelectedItem(
                tblRedeem.getValueAt(row, 1).toString()
        );

    }//GEN-LAST:event_tblRedeemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTukarPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTukarPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTukarPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTukarPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTukarPoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel2;
    private javax.swing.JButton btnKonfirmasi1;
    private javax.swing.JButton btnKonfirmasi2;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnMenuUtama3;
    private javax.swing.JButton btnPanduan2;
    private javax.swing.JButton btnSetor3;
    private javax.swing.JButton btnTukarPoint3;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbah1;
    private javax.swing.JComboBox<String> cbReward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPoin;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JTable tblPickup;
    private javax.swing.JTable tblRedeem;
    // End of variables declaration//GEN-END:variables

    private void tampilPoin() {
        if (Sessions.user != null) {
            lblPoin.setText(String.valueOf(Sessions.user.getPoin()));
        }
    }

    private int ambilPoinDariReward(String reward) {
        int start = reward.lastIndexOf("(");
        int end = reward.lastIndexOf(")");

        String poin = reward.substring(start + 1, end);
        return Integer.parseInt(poin);

    }

    private void loadData() {
        int idUser = Sessions.user.getId_user();

        DefaultTableModel model = (DefaultTableModel) tblRedeem.getModel();
        model.setRowCount(0);

        RedeemDAO dao = new RedeemDAO();
        ResultSet rs = dao.getRedeemByUser(idUser);

        try {
            while (rs != null && rs.next()) {
                Object[] row = {
                    rs.getInt("id_redeem"),
                    rs.getString("reward_text"),
                    rs.getInt("poin_dipakai"),
                    rs.getTimestamp("tanggal_redeem"),
                    rs.getString("status")
                };
                model.addRow(row);
            }

            // jika kosong
            if (model.getRowCount() == 0) {
                lblInfo.setText("Belum ada penukaran poin");
                lblInfo.setVisible(true);
            } else {
                lblInfo.setVisible(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data penukaran poin");
            e.printStackTrace();
        }

    }

    private void resetSelection() {
        selectedRedeemId = -1;
        selectedStatus = null;
        selectedPoin = 0;

    }
}
