/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin.permintaan;

import dao.PickupRequestDAO;
import dao.UserDAO;
import helper.PetugasItem;
import helper.Sessions;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.admin.datamaster.DataPetugas;
import view.admin.datamaster.DataRedeem;
import view.admin.datamaster.DataUser;
import view.auth.FormLogin;

/**
 *
 * @author HYPE AMD
 */
public class PermintaanPickup extends javax.swing.JFrame {

    private DefaultTableModel model;
    private ArrayList<Integer> listIdPetugas = new ArrayList<>();

    /**
     * Creates new form PermintaanPickup
     */
    public PermintaanPickup() {
        if (Sessions.user == null) {
            JOptionPane.showMessageDialog(this,
                    "Silakan login terlebih dahulu");
            new FormLogin().setVisible(true);
            return;
        }
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        tblPickup.setModel(model);
        model.addColumn("ID_Request");
        model.addColumn("Nama");
        model.addColumn("Jenis Sampah");
        model.addColumn("Alamat Pickup");
        model.addColumn("Status");
        model.addColumn("Petugas");
        cbStatus.removeAllItems();
        cbStatus.addItem("menunggu");
        cbStatus.addItem("terkirim");
        cbStatus.addItem("terverifikasi");
        cbStatus.addItem("selesai");
        loadDataPetugas();
        loadDataPickup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MenuPanel = new javax.swing.JPanel();
        btnPanduan = new javax.swing.JButton();
        btnSetor1 = new javax.swing.JButton();
        btnTukarPoint1 = new javax.swing.JButton();
        btnMenuUtama1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnTugas = new javax.swing.JButton();
        cbPetugas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPickup = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        btnUbahStatus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        MenuPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnDataMaster = new javax.swing.JButton();
        btnPermintaan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlSubMenu = new javax.swing.JPanel();
        lblDataPetugas = new javax.swing.JLabel();
        lblDataUser = new javax.swing.JLabel();
        lblDataUser1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        MenuPanel.setBackground(new java.awt.Color(153, 204, 0));

        btnPanduan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPanduan.setForeground(new java.awt.Color(153, 204, 0));
        btnPanduan.setText("Panduan");
        btnPanduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanduanActionPerformed(evt);
            }
        });

        btnSetor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSetor1.setForeground(new java.awt.Color(153, 204, 0));
        btnSetor1.setText("Setor");
        btnSetor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetor1ActionPerformed(evt);
            }
        });

        btnTukarPoint1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTukarPoint1.setForeground(new java.awt.Color(153, 204, 0));
        btnTukarPoint1.setText("Tukar Point");
        btnTukarPoint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTukarPoint1ActionPerformed(evt);
            }
        });

        btnMenuUtama1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuUtama1.setForeground(new java.awt.Color(153, 204, 0));
        btnMenuUtama1.setText("Home");
        btnMenuUtama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtama1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPanduan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSetor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTukarPoint1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnMenuUtama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnMenuUtama1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPanduan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnTukarPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Petugas");

        btnTugas.setBackground(new java.awt.Color(153, 204, 0));
        btnTugas.setText("Tugaskan");
        btnTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTugasActionPerformed(evt);
            }
        });

        cbPetugas.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Permintaan Pickup");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detail Permintaan Pickup");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHapus.setBackground(new java.awt.Color(153, 204, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblPickup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPickup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPickupMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPickup);

        jScrollPane1.setViewportView(jScrollPane4);

        jLabel4.setText("Status Pickup");

        cbStatus.setBackground(new java.awt.Color(204, 204, 204));

        btnUbahStatus.setBackground(new java.awt.Color(153, 204, 0));
        btnUbahStatus.setText("Ubah Status");
        btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(153, 204, 0));
        btnCetak.setText("Cetak Laporan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addGap(110, 110, 110))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTugas)
                    .addComponent(btnHapus)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahStatus)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );

        MenuPanel1.setBackground(new java.awt.Color(153, 204, 0));

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(153, 204, 0));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDataMaster.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDataMaster.setForeground(new java.awt.Color(153, 204, 0));
        btnDataMaster.setText("Data Master  ▼");
        btnDataMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMasterActionPerformed(evt);
            }
        });

        btnPermintaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPermintaan.setForeground(new java.awt.Color(153, 204, 0));
        btnPermintaan.setText("Permintaan Pickup");
        btnPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermintaanActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(153, 204, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        pnlSubMenu.setBackground(new java.awt.Color(153, 204, 0));

        lblDataPetugas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataPetugas.setForeground(new java.awt.Color(255, 255, 255));
        lblDataPetugas.setText("Data Petugas");
        lblDataPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataPetugasMouseClicked(evt);
            }
        });

        lblDataUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataUser.setForeground(new java.awt.Color(255, 255, 255));
        lblDataUser.setText("Data User");
        lblDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataUserMouseClicked(evt);
            }
        });

        lblDataUser1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblDataUser1.setText("Data Redeem");
        lblDataUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataUser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSubMenuLayout = new javax.swing.GroupLayout(pnlSubMenu);
        pnlSubMenu.setLayout(pnlSubMenuLayout);
        pnlSubMenuLayout.setHorizontalGroup(
            pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubMenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataPetugas)
                    .addComponent(lblDataUser)
                    .addComponent(lblDataUser1))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlSubMenuLayout.setVerticalGroup(
            pnlSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDataPetugas)
                .addGap(18, 18, 18)
                .addComponent(lblDataUser)
                .addGap(18, 18, 18)
                .addComponent(lblDataUser1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuPanel1Layout = new javax.swing.GroupLayout(MenuPanel1);
        MenuPanel1.setLayout(MenuPanel1Layout);
        MenuPanel1Layout.setHorizontalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDataMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPermintaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        MenuPanel1Layout.setVerticalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanduanActionPerformed
        // TODO add your handling code here:
//        FormPanduan panduan = new FormPanduan();
//
//        panduan.setVisible(true);
//
//        this.dispose();
    }//GEN-LAST:event_btnPanduanActionPerformed

    private void btnSetor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetor1ActionPerformed
        // TODO add your handling code here:
//        FormSetor setor = new FormSetor();
//        setor.setLocationRelativeTo(null); // Membuat window muncul di tengah
//        setor.setVisible(true);
//        this.dispose(); //
    }//GEN-LAST:event_btnSetor1ActionPerformed

    private void btnTukarPoint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTukarPoint1ActionPerformed
        // TODO add your handling code here:
//        FormTukarPoint ftp = new FormTukarPoint();
//        ftp.setLocationRelativeTo(null); // Agar muncul di tengah layar
//        ftp.setVisible(true);
//
//        // Menutup Dashboard
//        this.dispose();
    }//GEN-LAST:event_btnTukarPoint1ActionPerformed

    private void btnMenuUtama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtama1ActionPerformed
        // TODO add your handling code here:
//        new FormDashboard().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnMenuUtama1ActionPerformed

    private void btnTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTugasActionPerformed
        // TODO add your handling code here:
        int idRequest = getSelectedIdRequest();
        if (idRequest == -1) {
            return;
        }

        int indexPetugas = cbPetugas.getSelectedIndex();
        if (indexPetugas == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih petugas terlebih dahulu");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menugaskan petugas untuk pickup ini?",
                "Konfirmasi Penugasan",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        int idPetugas = listIdPetugas.get(indexPetugas);

        PickupRequestDAO dao = new PickupRequestDAO();
        boolean sukses = dao.tugaskanPickup(idRequest, idPetugas);

        if (sukses) {
            JOptionPane.showMessageDialog(this,
                    "Pickup berhasil ditugaskan");
            loadDataPickup();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal menugaskan pickup");
        }

    }//GEN-LAST:event_btnTugasActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblPickup.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data pickup terlebih dahulu");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah yakin ingin menghapus permintaan pickup ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

        int idRequest = Integer.parseInt(
                tblPickup.getValueAt(row, 0).toString()
        );

        PickupRequestDAO dao = new PickupRequestDAO();
        boolean sukses = dao.deletePickup(idRequest);

        if (sukses) {
            JOptionPane.showMessageDialog(this,
                    "Permintaan pickup berhasil dihapus");
            loadDataPickup();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal menghapus permintaan pickup");
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahStatusActionPerformed
        // TODO add your handling code here:
        int row = tblPickup.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data pickup terlebih dahulu");
            return;
        }

        int idRequest = Integer.parseInt(
                tblPickup.getValueAt(row, 0).toString()
        );

        String statusBaru = cbStatus.getSelectedItem().toString();

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Ubah status pickup menjadi \"" + statusBaru + "\" ?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

        PickupRequestDAO dao = new PickupRequestDAO();
        boolean sukses = dao.updateStatusPickup(idRequest, statusBaru);

        if (sukses) {
            JOptionPane.showMessageDialog(this,
                    "Status pickup berhasil diubah");
            loadDataPickup();

            cbStatus.setEnabled(false);
            btnUbahStatus.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengubah status pickup");
        }

    }//GEN-LAST:event_btnUbahStatusActionPerformed

    private void tblPickupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPickupMouseClicked
        // TODO add your handling code here:
        int row = tblPickup.getSelectedRow();
        if (row == -1) {
            return;
        }

        String status = tblPickup.getValueAt(row, 4).toString();

        cbStatus.setSelectedItem(status);
        cbStatus.setEnabled(true);
        btnUbahStatus.setEnabled(true);
    }//GEN-LAST:event_tblPickupMouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        cetakLaporan();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDataMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMasterActionPerformed
        // TODO add your handling code here:
        pnlSubMenu.setVisible(!pnlSubMenu.isVisible());
        MenuPanel.revalidate();
        MenuPanel.repaint();

    }//GEN-LAST:event_btnDataMasterActionPerformed

    private void btnPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermintaanActionPerformed
        // TODO add your handling code here:
        new PermintaanPickup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPermintaanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

        Sessions.logout();

        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblDataPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataPetugasMouseClicked
        // TODO add your handling code here:
        new DataPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDataPetugasMouseClicked

    private void lblDataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataUserMouseClicked
        // TODO add your handling code here:
        new DataUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDataUserMouseClicked

    private void lblDataUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataUser1MouseClicked
        // TODO add your handling code here:
        new DataRedeem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDataUser1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermintaanPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermintaanPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermintaanPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermintaanPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermintaanPickup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel MenuPanel1;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataMaster;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuUtama1;
    private javax.swing.JButton btnPanduan;
    private javax.swing.JButton btnPermintaan;
    private javax.swing.JButton btnSetor1;
    private javax.swing.JButton btnTugas;
    private javax.swing.JButton btnTukarPoint1;
    private javax.swing.JButton btnUbahStatus;
    private javax.swing.JComboBox<String> cbPetugas;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDataPetugas;
    private javax.swing.JLabel lblDataUser;
    private javax.swing.JLabel lblDataUser1;
    private javax.swing.JPanel pnlSubMenu;
    private javax.swing.JTextField search;
    private javax.swing.JTable tblPickup;
    // End of variables declaration//GEN-END:variables

    private void loadDataPetugas() {
        cbPetugas.removeAllItems();
        listIdPetugas.clear();

        UserDAO dao = new UserDAO();
        ResultSet rs = dao.getAllPetugas();

        try {
            while (rs != null && rs.next()) {
                int id = rs.getInt("id_user");
                String nama = rs.getString("nama");

                cbPetugas.addItem(nama);
                listIdPetugas.add(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load petugas");
        }

    }

    private void loadDataPickup() {
        DefaultTableModel model = (DefaultTableModel) tblPickup.getModel();
        model.setRowCount(0);

        PickupRequestDAO dao = new PickupRequestDAO();
        ResultSet rs = dao.getAllPickup();

        try {
            while (rs != null && rs.next()) {
                Object[] row = {
                    rs.getInt("id_request"),
                    rs.getString("nama_user"),
                    rs.getString("jenis_sampah"),
                    rs.getString("alamat_pickup"),
                    rs.getString("status"),
                    rs.getString("nama_petugas")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load pickup");
        }

    }

    private int getSelectedIdRequest() {
        int row = tblPickup.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data pickup terlebih dahulu");
            return -1;
        }
        return Integer.parseInt(
                tblPickup.getValueAt(row, 0).toString()
        );
    }

    public void cetakLaporan() {
        try {
            MessageFormat header
                    = new MessageFormat("Laporan Data Pickup YoGreen");

            MessageFormat footer
                    = new MessageFormat("Halaman {0}");

            tblPickup.print(
                    JTable.PrintMode.FIT_WIDTH,
                    header,
                    footer
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan");
        }
    }

}
